version: "3"

services:
  # postgresql database + pg_vector extension
  db:
    image: ghcr.io/kreneskyp/ix/postgres-pg-vector:15.3
    environment:
      POSTGRES_PASSWORD: ix
      POSTGRES_USER: ix
      POSTGRES_DB: ix
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app server: HTTP/asgi, websockets, django
  web:
    image: ghcr.io/kreneskyp/ix/sandbox:latest
    command: uvicorn ix.server.asgi:application --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    links:
      - db
      - redis
      - vault
    volumes:
      - .:/var/app
      - ./bin:/usr/bin/ix
      - .bash_profile:/root/.bash_profile
      - .ipython:/root/.ipython
      - ./.certs/:/var/vault/certs:ro,Z
    env_file:
      - .env
      - .vault/.client.env
    environment:
      VAULT_BASE_PATH: "ix"
      DJANGO_SETTINGS_MODULE: "ix.server.settings"

  # Main entry to app: static content, HTTP 1.1, websockets, proxy to app server
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.compiled-static:/var/static/
    depends_on:
      - web

  # Agent worker: celery, django
  worker:
    image: ghcr.io/kreneskyp/ix/sandbox:latest
    command: celery.sh
    links:
      - db
      - redis
      - vault
      - chroma
    volumes:
      - .:/var/app
      - .node_modules:/var/npm/node_modules
      - ./bin:/usr/bin/ix
      - .bash_profile:/root/.bash_profile
      - ./.certs/:/var/vault/certs:ro,Z
    env_file:
      - .env
      - .vault/.client.env
    environment:
      VAULT_BASE_PATH: "ix"
      DJANGO_SETTINGS_MODULE: "ix.server.settings"

  # nodejs / frontend builder
  nodejs:
    image: ghcr.io/kreneskyp/ix/nodejs:latest
    volumes:
      - ./frontend:/var/app/frontend
      - ./package.json:/var/app/package.json
      - ./package-lock.json:/var/app/package-lock.json
      - ./babel.config.js:/var/app/babel.config.js
      - ./relay.config.js:/var/app/relay.config.js
      - ./webpack.config.js:/var/app/webpack.config.js
      - ./bin:/usr/bin/ix
      - .compiled-static:/var/app/.compiled-static
    env_file:
      - .env

  redis:
    image: redis/redis-stack-server:latest

  chroma:
    image: ghcr.io/chroma-core/chroma:0.4.13
    ports:
      - "8020:8000"

  vault:
    image: hashicorp/vault:1.14
    volumes:
    - ./vault:/vault/config/
    - ./.certs/:/vault/certs
    - .vault/file:/vault/file
    command: "server"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK

volumes:
  postgres_data:
