version: "3"

services:
  db:
    image: postgres:14.7
    environment:
      POSTGRES_PASSWORD: ix
      POSTGRES_USER: ix
      POSTGRES_DB: ix
      POSTGRES_HOST_AUTH_METHOD: trust

  sandbox:
    image: ghcr.io/ix:latest
    links:
      - db
      - redis
    volumes:
      - .:/var/app
      #- .node_modules:/var/npm/node_modules
      - ./bin:/usr/bin/ix
      - .bash_profile:/root/.bash_profile
    env_file:
      - .env
    ports:
      - "8000:8000"

  worker:
    image: ghcr.io/ix:latest
    command: celery.sh
    links:
      - db
      - redis
    volumes:
      - .:/var/app
      #- .node_modules:/var/npm/node_modules
      - ./bin:/usr/bin/ix
      - .bash_profile:/root/.bash_profile
    env_file:
      - .env



  redis:
    image: redis

